# run: conda env create -f environment.yml -q

name: bera
channels:
  - nodefaults
  - appliedgrg
  - conda-forge
dependencies:
  - python=3.11
  - appliedgrg::bera_centerlines
  - appliedgrg::beratools
  - dask
  - gdal=3.9.3
  - geopandas
  - pyogrio>=0.9.0
  - pyqt
  - rasterio
  - scikit-image>=0.24.0
  - tqdm
  - xarray-spatial
variables:
