[workspace]
authors = ["Richard <502763+RichardQZeng@users.noreply.github.com>"]
channels = ["nodefaults", "appliedgrg", "conda-forge"]
description = "BERA Tools is toolset to extract and assess line features in forest"
name = "bera"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
main_tk = "python main.py"
main = "python ./beratools/gui/main.py"

[dependencies]
python = "3.11.*"
bera_centerlines = { channel = "appliedgrg" }
dask = "*"
gdal = "3.9.3.*"
geopandas = "*"
pyarrow = "*"
pyogrio = ">=0.9.0"
pyqt = "*"
rasterio = "*"
scikit-image = ">=0.24.0"
tqdm = "*"
xarray-spatial = "*"
pytest = "*"

[pypi-dependencies]
hatch-vcs = "*"
