[tox]
envlist = py312,py313,py314
requires = 
    tox>=4.0
    tox-uv
skipsdist = False

[testenv]
description = Run package tests with pytest in an isolated env
package = skip
skip_install = true
sitepackages = true
commands =
     pytest -vv -s --maxfail=1 --log-cli-level=INFO tests/test_workflow.py
setenv =
    PYTHONDONTWRITEBYTECODE = 1

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13

[testenv:py314]
basepython = python3.14
