# config.yaml for hydra

DATA_DIR: F:/
CHM: Study_Site_CHM_Projected.tif
SEEDLINE_GPKG: Study_Site_Center_Lines_new.shp
SEEDLINE_LAYER: Study_Site_Center_Lines_new

parallel_mode: 2
processes: null

steps_to_run:
  # - centerline
  - footprint_abs
  # - footprint_rel
  # - footprint_fixed

args_centerline:
  in_line: ${DATA_DIR}/${SEEDLINE_GPKG}
  in_layer: ${SEEDLINE_LAYER}
  in_raster: ${DATA_DIR}/${CHM}
  line_radius: 15
  proc_segments: true
  out_line: ${DATA_DIR}/centerline.gpkg
  out_layer: centerline
  verbose: false

args_footprint_abs:
  in_line: ${DATA_DIR}/centerline.gpkg
  in_layer: centerline
  in_chm: ${DATA_DIR}/${CHM}
  corridor_thresh: 3.0
  max_ln_width: 32.0
  exp_shk_cell: 0
  out_footprint: ${DATA_DIR}/footprint_abs.gpkg
  out_layer: footprint_abs
  verbose: false

args_footprint_rel:
  in_line: ${DATA_DIR}/centerline.gpkg
  in_layer: centerline
  in_chm: ${DATA_DIR}/${CHM}
  out_footprint: ${DATA_DIR}/footprint_rel.gpkg
  out_layer: footprint_rel
  max_ln_width: 32
  tree_radius: 1.5
  max_line_dist: 1.5
  canopy_avoidance: 0.0
  exponent: 0
  canopy_thresh_percentage: 50
  verbose: false

args_footprint_fixed:
  in_line: ${DATA_DIR}/centerline.gpkg
  in_footprint: ${DATA_DIR}/footprint_rel.gpkg
  in_layer: centerline
  in_layer_fp: footprint_rel
  n_samples: 15
  offset: 30
  max_width: null
  width_percentile: 60
  out_footprint: ${DATA_DIR}/footprint_final.gpkg
  out_layer: footprint_fixed
  verbose: false
  merge_group: false

args_split_lines:
  input_gpkg: ${DATA_DIR}/footprint_final.gpkg
  layer_name: merged_lines_original

args_footprint_inter:
  in_line: ${DATA_DIR}/footprint_final.gpkg
  in_footprint: ${DATA_DIR}/footprint_rel.gpkg
  in_layer: split_lines
  in_layer_fp: footprint_rel
  n_samples: 15
  offset: 30
  max_width: true
  out_footprint: ${DATA_DIR}/footprint_intersection.gpkg
  out_layer: clean_footprint
  verbose: false
  merge_group: false
