{% set name = "BERATools" %}
{% set git_tag = environ.get('GIT_TAG', 'main') %}
{% set version = environ.get('VERSION', '0.1.0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/appliedgrg/beratools.git
  git_tag: {{ git_tag }}

build:
  entry_points:
    - BERATools = beratools.gui:gui_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
  run:
    - python >=3.10
    - bera_centerlines
    - dask
    - gdal
    - geopandas
    - pyarrow
    - pyogrio
    - pyqt
    - rasterio
    - scikit-image
    - tqdm
    - xarray-spatial

test:
  imports:
    - beratools
  commands:
    - pytest ./tests
  source_files:
    - tests

  requires:
    - pip

about:
  home: https://github.com/appliedgrg/beratools.git
  summary: An advanced forest line feature analysis platform
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - richard
