site_name: BERA Tools Guide
theme:
  name: material

docs_dir: files
watch:
  - files

# page tree
nav: 
  - User Guide: index.md
  - Developer Guid: developer_guide.md
  - API Reference: api.md

plugins:
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
