site_name: BERA Tools Guide

theme:
  name: material
  repo_url: https://github.com/appliedgrg/beratools
  repo_name: GitHub
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"

  features:
    - navigation.tabs          # top-level tabs in the header
    - navigation.top           # keep nav in header
    - content.code.copy        # optional niceties
    - content.action.edit
  font:
    text: Inter
    code: JetBrains Mono
  favicon: icons/bera_logo.png
  logo: icons/bera_logo.svg

repo_url: https://github.com/appliedgrg/beratools
repo_name: BERA Tools
edit_uri: edit/main/docs/files/

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - css/extra.css

docs_dir: files
watch:
  - files

# page tree
nav:
  - Home: 
    - index.md
    - about.md
  - User Guide: 
    - user_guide.md
    - start/installation.md
    - start/quick_start.md
    - Tools:
      - start/check_seed_line.md
      - start/vertex_optimization.md
      - start/centerline.md
      - start/line_footprint_abs.md
      - start/line_footprint_rel.md
      - start/line_footprint_fixed.md
  - Developer Guide:
    - developer_guide.md
    - developer/contributing.md
    - developer/development.md
    - developer/tool_template.md
  - API Reference: api.md

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
