name: CI — tox (venv)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.11"
            toxenv: py311
          - python-version: "3.12"
            toxenv: py312
          - python-version: "3.13"
            toxenv: py313
          - python-version: "3.14"
            toxenv: py314

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-${{ matrix.python-version }}-

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run tests via tox
        run: tox -e ${{ matrix.toxenv }}