name: Deploy Docs to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test-docs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install GDAL system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          gdal-config --version
      - name: Install documentation dependencies
        run: |
          pip install "gdal==3.8.4"
          pip install -r docs/files/requirements.txt
      - name: Install project in editable mode
        run: pip install -e .
      - name: Build docs site
        run: zensical build -f docs/mkdocs.yml

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install GDAL system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          gdal-config --version
      - name: Install documentation dependencies
        run: |
          pip install "gdal==3.8.4"
          pip install -r docs/files/requirements.txt
      - name: Install project in editable mode
        run: pip install -e .
      - name: Build docs site
        run: zensical build -f docs/mkdocs.yml
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
