name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Verify tag is on main branch
        run: |
          git fetch origin main
          if ! git branch --contains $GITHUB_SHA | grep -q 'main'; then
            echo "Tag is not from main branch. Skipping publish."
            exit 0
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install build tools
        run: pip install build twine hatch-vcs
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
