name: Python Tests by Pixi

on:
  push:
    branches:
      - main
    paths:
      - 'beratools/**'
  pull_request:
    branches:
      - main
    paths:
      - 'beratools/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out code"
        run: echo "Checking out code"
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GDAL system libs
        run: |
          echo "Installing GDAL system libraries"
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          gdal-config --version

      - name: Install Pixi
        run: echo "Installing Pixi" && curl -fsSL https://pixi.sh/install.sh | bash

      - name: Setup Pixi Environment
        run: |
          echo "Setting up Pixi environment"
          export PATH="$HOME/.pixi/bin:$PATH"
          pixi install

      - name: Editable Install of beratools
        run: |
          echo "Installing beratools in editable mode"
          export PATH="$HOME/.pixi/bin:$PATH"
          pip install -e .

      - name: Run Tests
        run: |
          echo "Running pytest"
          export PATH="$HOME/.pixi/bin:$PATH"
          pytest tests/test_workflow.py --maxfail=1 --disable-warnings -s -v
